### ISSUE TITLE
lubeck documentation tests fail

### ISSUE THREAD

**Issue by tastyminerals** [kaleidicassociates/lubeck#36] opened 2020-08-02 10:09 UTC
The following tests are failing currently:

- detSymmetric
- eigSymmetric
- luSolve
- ldlSolve
- choleskyDecomp
- qrSolve

Additionally, I think it would be better if examples included `import kaleidic.lubeck;` since the newcomers will be confused by having `import mir.ndslice;` but things not working.

Documentation contains redundant backward slashes here and there: `\min ||A * X - B|| Using the QR factorization: \A = Q * R`

**Comment by jmh530** [comment] 2020-08-02 23:25
@tastymaterials I don't see any errors in the CI and running `dub test` does not produce errors. Could you provide a little more information, such as an example of an offending line, what you did to generate the error, and what the error looks like?

**Comment by tastyminerals** [comment] 2020-08-03 17:28
My mistake, I totally forgot to write that these are the ddoc tests here: http://lubeck.libmir.org/kaleidic_lubeck.html

**Comment by jmh530** [comment] 2020-08-03 20:22
@tastyminerals I suspect this issue is related to the other about needing to tag a new release.

**Comment by tastyminerals** [comment] 2020-08-03 21:13
So, should I close it then and wait for that tag release of lubeck?

**Comment by jmh530** [comment] 2020-08-04 00:43
@tastyminerals I would wait for the new tag and then test that it works before closing.

**Comment by 9il** [comment] 2020-08-04 09:15
I have added a new release. However, the problem is that mir-algorithm version hasn't been updated at run.dlang.org machine.

**Closed** 2020-08-04 09:17 UTC
